import Papa from "papaparse";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { SCHOOL_NAME } from "@/lib/constants";
import { formatDate, formatDateTime } from "@/lib/utils";

export interface ExportMeta {
  reportTitle: string;
  filters?: string;
  generatedBy?: string;
}

export function exportToCSV(
  data: Record<string, unknown>[],
  filename: string,
  meta?: ExportMeta
) {
  const rows = data.length ? data : [{ message: "No data available" }];
  const csv = Papa.unparse(rows);
  const header = meta
    ? `# ${SCHOOL_NAME}\n# ${meta.reportTitle}\n# Generated: ${formatDateTime(new Date())}${meta.filters ? `\n# Filters: ${meta.filters}` : ""}${meta.generatedBy ? `\n# Generated By: ${meta.generatedBy}` : ""}\n\n`
    : "";
  downloadBlob(new Blob([header + csv], { type: "text/csv;charset=utf-8;" }), `${filename}.csv`);
}

export function exportToPDF(
  columns: { header: string; dataKey: string }[],
  data: Record<string, unknown>[],
  filename: string,
  meta: ExportMeta
) {
  const doc = new jsPDF();
  doc.setFontSize(14);
  doc.text(SCHOOL_NAME, 14, 15);
  doc.setFontSize(11);
  doc.text("LIBRARY SERVICES", 14, 22);
  doc.setFontSize(12);
  doc.text(meta.reportTitle, 14, 32);
  doc.setFontSize(9);
  doc.text(`Generated: ${formatDateTime(new Date())}`, 14, 39);
  if (meta.generatedBy) doc.text(`Generated By: ${meta.generatedBy}`, 14, 44);
  if (meta.filters) doc.text(`Filters: ${meta.filters}`, 14, 49);

  autoTable(doc, {
    startY: meta.filters ? 54 : 49,
    head: [columns.map((c) => c.header)],
    body: data.map((row) => columns.map((c) => String(row[c.dataKey] ?? ""))),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [0, 32, 148] },
  });

  doc.save(`${filename}.pdf`);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export { formatDate, formatDateTime };
